;Calendar Settings

[Variables]

size=#SizeCalendar#

;Name of the Style Sheet
Style=Default

;Custom text for Weekday labels. Default:S|M|T|W|T|F|S
DayLabels=Sun|Mon|Tue|Wed|Thu|Fri|Sat

;Set to 1 to hide week 6 if not included in the current month. Default:0
HideLastWeek=0

;Allows for personalized formatting of the calendar title. Default:{$MName}, {$Year}.
LabelText={$MName}, {$Year}

;Custom text for Month labels. Default:1|2|3|4|5|6|7|8|9|10|11|12
MonthLabels=January|February|March|April|May|June|July|August|September|October|November|December

;Set to 1 to have the week start on Monday. Default:0
StartOnMonday=0


